name: tf_torch
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - matplotlib
  - scikit-learn=1.3.0
  - pip
  - python=3.9
  - pip:
    - numpy==1.24.3
    - pandas==2.0.3
    - Pillow==10.0.0
    - scipy==1.10.1
    - tensorflow==2.13.0
    - tensorflow-datasets==4.9.2
    - yfinance==0.2.*
    - -e .  # install local 
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch
    - torchvision
    - torchaudio
    - torchtext

    
